<?php

declare(strict_types=1);

namespace App\Controllers\Admin;

use App\Core\Auth;
use App\Core\Backup;
use App\Core\Cache;
use App\Core\Logger;
use App\Core\Request;
use App\Core\Response;
use Database\Database;

class BackupController
{
    public function index(Request $request): void
    {
        if (!Auth::isSuperAdmin()) {
            Response::redirect('/admin');
            return;
        }

        $dbSize = 0;
        try {
            $pdo = Database::getConnection();
            $row = $pdo->query("
                SELECT SUM(data_length + index_length) as size
                FROM information_schema.TABLES
                WHERE table_schema = DATABASE()
            ")->fetch(\PDO::FETCH_ASSOC);
            $dbSize = (int)($row['size'] ?? 0);
        } catch (\Throwable $e) {
            $dbSize = 0;
        }

        $uploadsDir = dirname(__DIR__, 3) . '/uploads';
        $uploadsSize = $this->dirSize($uploadsDir);

        $settingsRows = Database::fetchAll("
            SELECT `key`, `value` FROM settings
            WHERE `key` IN ('backup_auto_enabled', 'backup_auto_interval_hours', 'backup_last_auto_at')
        ");
        $autoSettings = [];
        foreach ($settingsRows as $row) {
            $autoSettings[$row['key']] = $row['value'];
        }

        Response::view('admin/backup', [
            'backups' => Backup::listBackups(),
            'dbSizeFormatted' => Cache::formatSize($dbSize),
            'uploadsSizeFormatted' => Cache::formatSize($uploadsSize),
            'autoEnabled' => ($autoSettings['backup_auto_enabled'] ?? '0') === '1',
            'autoIntervalHours' => (int)($autoSettings['backup_auto_interval_hours'] ?? 24),
            'autoLastRunAt' => $autoSettings['backup_last_auto_at'] ?? null,
            'generated' => $request->get('generated') == 1,
            'deleted' => $request->get('deleted') == 1,
            'restored' => $request->get('restored') == 1,
            'autoSaved' => $request->get('auto_saved') == 1,
        ], 'admin');
    }

    public function generate(Request $request): void
    {
        if (!Auth::isSuperAdmin()) {
            Response::json(['success' => false, 'error' => 'Forbidden'], 403);
            return;
        }

        try {
            $zipPath = Backup::createFullBackupZip();
            $fileName = basename($zipPath);
            $fileSize = filesize($zipPath);

            Logger::info("Full backup generated by " . (Auth::user()['name'] ?? 'admin'), [
                'file' => $fileName,
                'size' => $fileSize
            ], 'system');

            if ($request->isAjax()) {
                Response::json([
                    'success' => true,
                    'message' => 'تم إنشاء النسخة الاحتياطية الكاملة بنجاح',
                    'backup' => [
                        'name' => $fileName,
                        'size_formatted' => Cache::formatSize((int)$fileSize),
                        'download_url' => url('/admin/backup/download?file=' . urlencode($fileName)),
                    ]
                ]);
                return;
            }

            Response::redirect('/admin/backup?generated=1');
        } catch (\Throwable $e) {
            Logger::error("Full backup generation failed: " . $e->getMessage(), [], 'system');

            if ($request->isAjax()) {
                Response::json(['success' => false, 'error' => $e->getMessage()], 500);
                return;
            }

            Response::error('فشل إنشاء النسخة الاحتياطية: ' . $e->getMessage());
        }
    }

    public function download(Request $request): void
    {
        if (!Auth::isSuperAdmin()) {
            Response::error('Forbidden', 403);
            return;
        }

        $fileName = (string)$request->get('file', '');
        $path = Backup::resolveBackupPath($fileName);

        if (!$path) {
            Response::error('Backup file not found', 404);
            return;
        }

        header('Content-Description: File Transfer');
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . basename($path) . '"');
        header('Expires: 0');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');
        header('Content-Length: ' . filesize($path));
        readfile($path);
        exit;
    }

    public function delete(Request $request): void
    {
        if (!Auth::isSuperAdmin()) {
            Response::json(['success' => false, 'error' => 'Forbidden'], 403);
            return;
        }

        $fileName = (string)$request->get('file', '');
        $ok = Backup::deleteBackup($fileName);

        if ($ok) {
            Logger::info("Backup file deleted by " . (Auth::user()['name'] ?? 'admin'), ['file' => $fileName], 'system');
        }

        if ($request->isAjax()) {
            Response::json(['success' => $ok]);
            return;
        }

        Response::redirect('/admin/backup?deleted=' . ($ok ? 1 : 0));
    }

    /**
     * Restore the database (and uploads) from either an existing backup on the
     * server (pass `file`) or a freshly uploaded .zip/.sql file (pass `restore_file`).
     */
    public function restore(Request $request): void
    {
        if (!Auth::isSuperAdmin()) {
            Response::json(['success' => false, 'error' => 'Forbidden'], 403);
            return;
        }

        try {
            $existingFile = trim((string)$request->get('file', ''));

            if ($existingFile !== '') {
                $path = Backup::resolveBackupPath($existingFile);
                if (!$path) {
                    throw new \RuntimeException('Backup file not found.');
                }
                $result = Backup::restoreFromZip($path);
            } elseif (!empty($_FILES['restore_file']['name'])) {
                $result = $this->restoreFromUploadedFile($_FILES['restore_file']);
            } else {
                throw new \RuntimeException('No backup selected to restore.');
            }

            Logger::info("Database restored from backup by " . (Auth::user()['name'] ?? 'admin'), $result, 'system');

            if ($request->isAjax()) {
                Response::json(['success' => true, 'result' => $result]);
                return;
            }

            Response::redirect('/admin/backup?restored=1');
        } catch (\Throwable $e) {
            Logger::error("Backup restore failed: " . $e->getMessage(), [], 'system');

            if ($request->isAjax()) {
                Response::json(['success' => false, 'error' => $e->getMessage()], 500);
                return;
            }

            Response::error('فشل استرجاع النسخة الاحتياطية: ' . $e->getMessage());
        }
    }

    private function restoreFromUploadedFile(array $file): array
    {
        if ($file['error'] !== UPLOAD_ERR_OK) {
            throw new \RuntimeException('File upload failed.');
        }

        $maxSize = 200 * 1024 * 1024; // 200MB
        if ($file['size'] > $maxSize) {
            throw new \RuntimeException('The uploaded file is too large (max 200MB).');
        }

        $ext = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
        if (!in_array($ext, ['zip', 'sql'], true)) {
            throw new \RuntimeException('Only .zip or .sql backup files are supported.');
        }

        $tmpPath = Backup::backupDir() . '/_upload_' . uniqid() . '.' . $ext;
        if (!move_uploaded_file($file['tmp_name'], $tmpPath)) {
            throw new \RuntimeException('Could not save the uploaded file.');
        }

        try {
            return $ext === 'zip' ? Backup::restoreFromZip($tmpPath) : Backup::restoreFromSqlFile($tmpPath);
        } finally {
            @unlink($tmpPath);
        }
    }

    public function updateAutoSettings(Request $request): void
    {
        if (!Auth::isSuperAdmin()) {
            Response::json(['success' => false, 'error' => 'Forbidden'], 403);
            return;
        }

        $enabled = $request->get('auto_enabled') ? '1' : '0';
        $interval = (int)$request->get('interval_hours', 24);
        if (!in_array($interval, [6, 12, 24, 72, 168], true)) {
            $interval = 24;
        }

        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("
            INSERT INTO settings (`key`, `value`) VALUES (?, ?)
            ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)
        ");
        $stmt->execute(['backup_auto_enabled', $enabled]);
        $stmt->execute(['backup_auto_interval_hours', (string)$interval]);

        if (class_exists('\\App\\Core\\Cache')) {
            Cache::flush('settings');
        }

        Logger::info("Automatic backup schedule updated by " . (Auth::user()['name'] ?? 'admin'), [
            'enabled' => $enabled,
            'interval_hours' => $interval
        ], 'system');

        if ($request->isAjax()) {
            Response::json(['success' => true]);
            return;
        }

        Response::redirect('/admin/backup?auto_saved=1');
    }

    private function dirSize(string $dir): int
    {
        if (!is_dir($dir)) {
            return 0;
        }
        $size = 0;
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS)
        );
        foreach ($iterator as $file) {
            if ($file->isFile()) {
                $size += $file->getSize();
            }
        }
        return $size;
    }
}
